### ISSUE TITLE
Failure/Error: should execute.with_change... Parent directory does not exist

### ISSUE THREAD

**Issue by mmarod** [domcleal/rspec-puppet-augeas#16]
Getting a weird error when trying to use rspec-augeas-puppet 0.4.0... 
My spec_helper.rb is..

```
require 'rspec-puppet'
require 'rspec-puppet-augeas'
require 'puppetlabs_spec_helper/module_spec_helper'

fixture_path = File.expand_path(File.join(__FILE__, '..', 'fixtures'))

RSpec.configure do |c|
  c.augeas_fixtures = File.join(File.dirname(File.expand_path(__FILE__)), 'fixtures', 'augeas')
  c.module_path = File.join(fixture_path, 'modules')
  c.manifest_dir = File.join(fixture_path, 'manifests')
end
```

My test is...

```
  describe_augeas 'configure-logcheck', :lens => 'Shellvars', :target => 'etc/logcheck/logcheck.conf' do
    it 'should change SENDMAILTO' do
      should execute.with_change
      aug_get('SENDMAILTO').should == 'logcheck@example.com'
      should execute.idempotently
    end
  end
```

and the error is...

```
# rake spec
/usr/bin/ruby1.9.1 -I/var/lib/gems/1.9.1/gems/rspec-support-3.2.2/lib:/var/lib/gems/1.9.1/gems/rspec-core-3.2.3/lib /var/lib/gems/1.9.1/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color
..F

Failures:

  1) baseline::config::logcheck Augeas[configure-logcheck] should change SENDMAILTO
     Failure/Error: should execute.with_change
     RuntimeError:
       Got 1 failure(s) while initializing: File[/vagrant/modules/baseline/spec/fixtures/modules/apt/lib:/vagrant/modules/baseline/spec/fixtures/modules/augeasproviders_core/lib:/vagrant/modules/baseline/spec/fixtures/modules/augeasproviders_pam/lib:/vagrant/modules/baseline/spec/fixtures/modules/collectd/lib:/vagrant/modules/baseline/spec/fixtures/modules/concat/lib:/vagrant/modules/baseline/spec/fixtures/modules/firewall/lib:/vagrant/modules/baseline/spec/fixtures/modules/puppet/lib:/vagrant/modules/baseline/spec/fixtures/modules/stdlib/lib]: change from absent to directory failed: Cannot create /vagrant/modules/baseline/spec/fixtures/modules/apt/lib:/vagrant/modules/baseline/spec/fixtures/modules/augeasproviders_core/lib:/vagrant/modules/baseline/spec/fixtures/modules/augeasproviders_pam/lib:/vagrant/modules/baseline/spec/fixtures/modules/collectd/lib:/vagrant/modules/baseline/spec/fixtures/modules/concat/lib:/vagrant/modules/baseline/spec/fixtures/modules/firewall/lib:/vagrant/modules/baseline/spec/fixtures/modules/puppet/lib:/vagrant/modules/baseline/spec/fixtures/modules/stdlib/lib; parent directory /vagrant/modules/baseline/spec/fixtures/modules/apt/lib:/vagrant/modules/baseline/spec/fixtures/modules/augeasproviders_core/lib:/vagrant/modules/baseline/spec/fixtures/modules/augeasproviders_pam/lib:/vagrant/modules/baseline/spec/fixtures/modules/collectd/lib:/vagrant/modules/baseline/spec/fixtures/modules/concat/lib:/vagrant/modules/baseline/spec/fixtures/modules/firewall/lib:/vagrant/modules/baseline/spec/fixtures/modules/puppet/lib:/vagrant/modules/baseline/spec/fixtures/modules/stdlib does not exist
     # /var/lib/gems/1.9.1/gems/rspec-puppet-augeas-0.4.0/lib/rspec-puppet-augeas/fixtures.rb:51:in `apply'
     # /var/lib/gems/1.9.1/gems/rspec-puppet-augeas-0.4.0/lib/rspec-puppet-augeas/resource.rb:17:in `initialize'
     # /var/lib/gems/1.9.1/gems/rspec-puppet-augeas-0.4.0/lib/rspec-puppet-augeas/example/run_augeas_example_group.rb:69:in `new'
     # /var/lib/gems/1.9.1/gems/rspec-puppet-augeas-0.4.0/lib/rspec-puppet-augeas/example/run_augeas_example_group.rb:69:in `subject'
     # ./spec/classes/logcheck_spec.rb:25:in `block (3 levels) in <top (required)>'

Finished in 4.27 seconds (files took 2.56 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/classes/logcheck_spec.rb:24 # baseline::config::logcheck Augeas[configure-logcheck] should change SENDMAILTO

/usr/bin/ruby1.9.1 -I/var/lib/gems/1.9.1/gems/rspec-support-3.2.2/lib:/var/lib/gems/1.9.1/gems/rspec-core-3.2.3/lib /var/lib/gems/1.9.1/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color failed
```

Any ideas? The directories in the last argument of the error message all exist.

**Comment by mmarod** [comment]
Looks like this is a dupe of #15 -- Closing this one out
